### ISSUE TITLE
Very Interesting Project

### ISSUE THREAD

**Issue by mgifford** [davidtodd/landmarks#1]
I just wanted to briefly say that this code is being considered in relations from removing Skip to Main links in projects like Drupal.

Would be very interesting to look at other places where skip links are presently being used on other sites and where ARIA landmarks might be able to replace their role.  

Hopefully this is the type of function that gets brought into the default patterns of all modern browsers.  Not convinced of the N <-> P functionality, but (EDIT) you've done a great job of making that configurable.

**Comment by davidtodd** [comment]
Hi Mike. Thank you for the comments.
